# TODO DEPRECATE THIS FILE
# This file is used to create a SecretProviderClass for Azure Key Vault
# and mount the secrets in the pod using the Secrets Store CSI driver.
# It should not be part of the base chart and should be moved to a specific deployment
# chart when using the Azure Key Vault.
{{- if .Values.azure.aksSecretsProviderAvailable -}}

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-secret-provider-{{ $.Release.Name }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.azure.keyvault.clientId }}
    keyvaultName: {{ .Values.azure.keyvault.name }}
    tenantId: {{ .Values.azure.keyvault.tenantId }}
    objects: |
      array:
    {{- range $name, $value := .Values.azure.secretKeys }}
        - |
          objectName: {{ $value | replace "_" "-" }}
          objectType: secret
    {{- end }}
  secretObjects:
    - secretName: pgstac-secrets-{{ $.Release.Name }}
      type: Opaque
      data:
      {{- range $name, $value := .Values.azure.secretKeys }}
        - objectName: {{ $value | replace "_" "-" }}
          key: {{ $name }}
      {{- end }}

{{- end }}
