apiVersion: v2
name: eoapi-support

appVersion: "0.1.7"
version: "0.1.7"

dependencies:
  - name: metrics-server
    version: 7.4.12
    repository: https://charts.bitnami.com/bitnami

  # Prometheus for collection of metrics.
  # https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
  #
  - name: prometheus
    # NOTE: configuration for this dependency is handled in `eoapi-support/values.yaml.prometheus` values
    version: 27.37.0
    repository: https://prometheus-community.github.io/helm-charts

  # used to create custom metrics to autoscale on
  #
  - name: prometheus-adapter
    # NOTE: configuration for this dependency is handled in `eoapi-support/values.yaml.prometheus-adapter` values
    version: 5.1.0
    repository: https://prometheus-community.github.io/helm-charts

  # Grafana for dashboarding of metrics
  # https://github.com/grafana/helm-charts/tree/main/charts/grafana
  #
  - name: grafana
    # NOTE: configuration for this dependency is handled in `eoapi-support/values.yaml.grafana` values
    version: 9.4.5
    repository: https://grafana.github.io/helm-charts
