{{- if .Values.apiServices }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eoapi-role-{{ $.Release.Name }}
  labels:
    app: eoapi-{{ $.Release.Name }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
---
{{- if .Values.knative.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eoapi-cluster-role-{{ $.Release.Name }}
  labels:
    app: eoapi-{{ $.Release.Name }}
rules:
# Knative operator resources
- apiGroups: ["operator.knative.dev"]
  resources: ["knativeservings", "knativeeventings"]
  verbs: ["get", "list", "create", "update", "patch", "watch"]
# Core resources needed by Knative
- apiGroups: [""]
  resources: ["namespaces", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "create", "update", "patch", "watch"]
# CRD management for Knative
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eoapi-cluster-rolebinding-{{ $.Release.Name }}
  labels:
    app: eoapi-{{ $.Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ include "eoapi.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: eoapi-cluster-role-{{ $.Release.Name }}
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eoapi-rolebinding-{{ $.Release.Name }}
  labels:
    app: eoapi-{{ $.Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ include "eoapi.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: Role
  name: eoapi-role-{{ $.Release.Name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
