ingress:
  host: "montandon-eoapi-stage.ifrc.org"
  tls:
    enabled: true
    secretName: montandon-eoapi-helm-secret-cert
  annotations:
    # increase the max body size to 100MB
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
raster:
  enabled: false
stac:
  image:
    name: ghcr.io/sunu/stac-fastapi-pgstac
    tag: 5.0.0-test7
  settings:
    labels:
      azure.workload.identity/use: "true"
    extraEnvVars:
      FORWARDED_ALLOW_IPS: "*"
      PROXY_HEADERS: True
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
    extraEnvFrom:
      - secretRef:
          name: pgstac-secrets-montandon-eoapi
    extraVolumeMounts:
      - name: azure-keyvault-secrets
        mountPath: /mnt/secrets-store
        readOnly: true
    extraVolumes:
      - name: azure-keyvault-secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-secret-provider-montandon-eoapi
  
vector:
  enabled: false

serviceAccount:
  create: true
  automount: true
  annotations:
    azure.workload.identity/client-id : "9b1f12a8-4ae9-4281-afa9-948451f77dce"
  labels:
    azure.workload.identity/use: "true"


pgstacBootstrap:
  enabled: true
  image:
    name: ghcr.io/stac-utils/pgstac
    tag: v0.9.5
  command:
    - "bash"
  args:
    - "-c"
    - "source /usr/local/bin/docker-entrypoint.sh && sh /opt/initdb/run-migrate-and-load.sh"
  settings:
    labels:
      azure.workload.identity/use: "true"
    extraEnvVars:
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
    extraEnvFrom:
      - secretRef:
          name: pgstac-secrets-montandon-eoapi
    extraVolumeMounts:
      - name: azure-keyvault-secrets
        mountPath: /mnt/secrets-store
        readOnly: true
    extraVolumes:
      - name: azure-keyvault-secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-secret-provider-montandon-eoapi
            
postgrescluster:
  enabled: false