{{- if .Values.raster.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-raster-envvar-configmap
data:
  {{- range $envKey, $envValue := .Values.raster.settings.envVars }}
  {{ upper $envKey }}: {{ $envValue | quote }}
  {{- end }}
{{- end }}
