apiVersion: v2
name: eoapi
description: Create a full Earth Observation API with Metadata, Raster and Vector services
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
kubeVersion: ">=1.23.0-0"

# Artifacthub metadata
icon: https://eoapi.dev/img/eoAPI.png
annotations:
  artifacthub.io/changes: |
    - Remove pathType and pathSuffix configurations
    - Add upgrade job for pre-0.7.0 migrations
    - Add separate browser ingress configuration
    - Support custom PostgreSQL cluster naming
  artifacthub.io/links: |
    - name: GitHub Repository
      url: https://github.com/developmentseed/eoapi-k8s
    - name: Documentation
      url: https://github.com/developmentseed/eoapi-k8s/tree/main/docs
  artifacthub.io/maintainers: |
    - name: DevelopmentSeed
      email: eoapi@developmentseed.org
  artifacthub.io/keywords: |
    - earth observation
    - geospatial
    - kubernetes
    - stac
    - raster
    - vector

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: "0.7.3"

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
# We use the stac-fastapi-pgstac version as the app version
appVersion: "5.0.2"

dependencies:
  - name: postgrescluster
    version: 5.7.4
    repository: "https://devseed.com/eoapi-k8s/"
    condition: postgrescluster.enabled
