# used in GH Actions `.github/workflows/helm-tests.yml.jobs.integration-tests`
testing: true
ingress:
  enabled: true
  className: "traefik"
pgstacBootstrap:
  enabled: true
  settings:
    resources:
      requests:
        cpu: "256m"
        memory: "1024Mi"
      limits:
        cpu: "512m"
        memory: "1024Mi"
raster:
  enabled: true
  settings:
    resources:
      limits:
        cpu: "768m"
        memory: "4096Mi"
      requests:
        cpu: "256m"
        memory: "1024Mi"
stac:
  enabled: true
  settings:
    resources:
      limits:
        cpu: "1280m"
        memory: "1536Mi"
      requests:
        cpu: "512m"
        memory: "1024Mi"
vector:
  enabled: true
  settings:
    resources:
      limits:
        cpu: "768m"
        memory: "1536Mi"
      requests:
        cpu: "256m"
        memory: "1024Mi"
    envVars:
      # needs to on so we can call /refresh for integration tests
      TIPG_DEBUG: "True"
