{{- if .Values.stac.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-stac-envvar-configmap
data:
  {{- range $envKey, $envValue := .Values.stac.settings.envVars }}
  {{ upper $envKey }}: {{ $envValue | quote }}
  {{- end }}
{{- end }}
