{{- if and .Values.stac.enabled .Values.stac.metrics.enabled .Values.stac.metrics.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-stac
  labels:
    {{- include "eoapi.labels" . | nindent 4 }}
    app.kubernetes.io/component: stac
    {{- with .Values.stac.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-stac
  endpoints:
    - port: http
      path: /_mgmt/metrics
      interval: {{ .Values.stac.metrics.serviceMonitor.interval }}
{{- end }}
