{{- if .Values.stac.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-stac
  labels:
    app: {{ .Release.Name }}-stac
  {{- if .Values.stac.annotations }}
  annotations:
    {{- with .Values.stac.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Release.Name }}-stac
{{- end }}
