{{- range $serviceName, $v := .Values -}}
{{- if has $serviceName $.Values.apiServices }}
{{- if index $v "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $serviceName }}-envvar-configmap-{{ $.Release.Name }}
data:
  {{- range $envKey, $envValue := index $v "settings" "envVars" }}
  {{ upper $envKey }}: {{ $envValue | quote }}
  {{- end }}
---
{{/* END: if index $v "enabled" */}}
{{- end }}
{{/* END: if has $serviceName $.Values.apiServices */}}
{{- end }}
{{/* END: range $serviceName, $v := .Values*/}}
{{- end }}
