{{- range $serviceName, $v := .Values -}}
{{- if (or (eq $serviceName "raster") (eq $serviceName "stac") (eq $serviceName "vector")) }}
{{- if index $v "enabled" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $serviceName }}-{{ $.Release.Name }}
    gitsha: {{ $.Values.gitSha }}
  name: {{ $serviceName }}-{{ $.Release.Name }}
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ $serviceName }}-{{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $serviceName }}-{{ $.Release.Name }}
    spec:
      containers:
      - image: {{ index $v "image" "name" }}:{{ index $v "image" "tag" }}
        {{- if (eq $.Values.providerContext "minikube") }}
        imagePullPolicy: Never
        {{- end }}
        name: {{ $serviceName }}
        command:
          {{- toYaml (index $v "command") | nindent 10 }}
          {{- if (and ($.Values.ingress.className) (eq $.Values.ingress.className "nginx") (not $.Values.testing)) }}
          - "--root-path=/{{ $serviceName }}"
          {{- else if (and ($.Values.ingress.className) (eq $.Values.ingress.className "nginx") ($.Values.testing)) }}
          - "--root-path=/{{ $serviceName }}{{ $.Release.Name }}"
          {{- end }}{{/* needed for proxies and path rewrites on NLB */}}
        livenessProbe:
          httpGet:
            {{- if (eq $serviceName "stac") }}
            path: /_mgmt/ping
            {{- else }}
            path: /healthz
            {{- end }}
            port: {{ $.Values.service.port }}
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 1
        ports:
          - containerPort: {{ $.Values.service.port }}
        resources:
          limits:
            cpu: {{ index $v "settings" "resources" "limits" "cpu" }}
            memory: {{ index $v "settings" "resources" "limits" "memory" }}
          requests:
            cpu: {{ index $v "settings" "resources" "requests" "cpu" }}
            memory: {{ index $v "settings" "resources" "requests" "memory" }}
        envFrom:
          # NOTE: there's no reason we need to use a `ConfigMap` or `Secret` here to get os env vars into the pod.
          # we could just template them out here immediately with `value: $_` but this allows us
          # to store them in k8s intermediately and change them and then bounce deploys if needed
        - secretRef:
            name: pgstac-secrets-{{ $.Release.Name }}
        - configMapRef:
            name: {{ $serviceName }}-envvar-configmap-{{ $.Release.Name }}
---
{{/* END: if index $v "enabled" */}}
{{- end }}
{{/* END: if (or (eq $serviceName "raster") (eq $serviceName "stac") (eq $serviceName "vector")) */}}
{{- end }}
{{/* END: range $serviceName, $v := .Values*/}}
{{- end }}
