{{- include "eoapi.validateAutoscaleRules" . -}}
{{- range $serviceName, $v := .Values -}}
{{- if (or (eq $serviceName "raster") (eq $serviceName "stac") (eq $serviceName "vector")) }}
{{- if index $v "autoscaling" "enabled" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-{{ $serviceName }}-{{ $.Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $serviceName }}-{{ $.Release.Name }}
  minReplicas: {{ index $v "autoscaling" "minReplicas" }}
  maxReplicas: {{ index $v "autoscaling" "maxReplicas" }}
  behavior:
    {{- toYaml (index $v "autoscaling" "behavior") | nindent 4 }}
  metrics:
  {{- if or (eq (index $v "autoscaling" "type") "cpu") (eq (index $v "autoscaling" "type") "both") }}
  # NOTE: 'Resource' are default metrics using k8s metrics-server
  # SEE: ../../../docs/autoscaling.md
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ index $v "autoscaling" "targets" "cpu" }}
  {{- end }}
  {{- if or (eq (index $v "autoscaling" "type") "requestRate") (eq (index $v "autoscaling" "type") "both") }}
  # NOTE: 'Object' are custom metrics using third-party plugins such as prometheus + prometheus-adapter
  # SEE: ../../../docs/autoscaling.md
  - type: Object
    object:
      metric:
        name: nginx_ingress_controller_requests_rate_{{ $serviceName }}_{{ $.Release.Name }}
      describedObject:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        name: nginx-service-ingress-shared-{{ $.Release.Name }}
      target:
        type: AverageValue
        averageValue: {{ index $v "autoscaling" "targets" "requestRate" }}
  {{- end }}
---
{{/* END: if index $v "autoscaling" "enabled" */}}
{{- end }}
{{/* END: if (or (eq $serviceName "raster") (eq $serviceName "stac") (eq $serviceName "vector")) */}}
{{- end }}
{{/* END: range $serviceName, $v := .Values*/}}
{{- end }}
