{{- if .Values.ingress.enabled }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: eoapi-ingress-{{ .Release.Name }}
  labels:
    app: eoapi-{{ .Release.Name }}
  annotations:
    {{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
    {{- end }}
    # Temporary annotations for Traefik until uvicorn support real prefix in ASGI: https://github.com/encode/uvicorn/discussions/2490
    {{- if eq .Values.ingress.className "traefik" }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: {{ $.Release.Namespace }}-strip-prefix-middleware-{{ $.Release.Name }}@kubernetescrd
    {{- end }}
    {{- if and .Values.ingress.tls.enabled .Values.ingress.tls.certManager .Values.ingress.tls.certManagerIssuer }}
    cert-manager.io/issuer: {{ .Values.ingress.tls.certManagerIssuer }}
    {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
      http:
        paths:
          {{- if and .Values.raster.enabled (or (not (hasKey .Values.raster "ingress")) .Values.raster.ingress.enabled) }}
          - pathType: {{ .Values.ingress.pathType }}
            path: /raster{{ .Values.ingress.pathSuffix }}
            backend:
              service:
                name: raster
                port:
                  number: {{ .Values.service.port }}
          {{- end }}
          
          {{- if and .Values.stac.enabled (or (not (hasKey .Values.stac "ingress")) .Values.stac.ingress.enabled) }}
          - pathType: {{ .Values.ingress.pathType }}
            path: /stac{{ .Values.ingress.pathSuffix }}
            backend:
              service:
                name: stac
                port:
                  number: {{ .Values.service.port }}
          {{- end }}
          
          {{- if and .Values.vector.enabled (or (not (hasKey .Values.vector "ingress")) .Values.vector.ingress.enabled) }}
          - pathType: {{ .Values.ingress.pathType }}
            path: /vector{{ .Values.ingress.pathSuffix }}
            backend:
              service:
                name: vector
                port:
                  number: {{ .Values.service.port }}
          {{- end }}
          
          {{- if and .Values.multidim.enabled (or (not (hasKey .Values.multidim "ingress")) .Values.multidim.ingress.enabled) }}
          - pathType: {{ .Values.ingress.pathType }}
            path: /multidim{{ .Values.ingress.pathSuffix }}
            backend:
              service:
                name: multidim
                port:
                  number: {{ .Values.service.port }}
          {{- end }}
          
          {{- if (and (.Values.browser.enabled) (not .Values.testing) (.Values.docServer.enabled)) }}
          # We need a separate path because browser does not play well with nginx rewrite_path directive
          - pathType: Prefix
            path: "/browser"
            backend:
              service:
                name: browser-{{ $.Release.Name }}
                port:
                  number: 8080
          {{- end }}
          
          {{- if .Values.docServer.enabled }}
          - pathType: {{ $.Values.ingress.pathType | default "Prefix" }}
            path: "/{{ $.Values.ingress.rootPath | default "" }}"
            backend:
              service:
                name: eoapi-doc-server
                port:
                  number: 80
          {{- end }}
  {{- if and .Values.ingress.host .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}
