{{- range $serviceName, $v := .Values -}}
{{- if has $serviceName $.Values.apiServices }}
{{- if index $v "enabled" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceName }}-sa-{{ $.Release.Name }}
  labels:
    app: {{ $serviceName }}-{{ $.Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $serviceName }}-role-{{ $.Release.Name }}
  labels:
    app: {{ $serviceName }}-{{ $.Release.Name }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $serviceName }}-rolebinding-{{ $.Release.Name }}
  labels:
    app: {{ $serviceName }}-{{ $.Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ $serviceName }}-sa-{{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: Role
  name: {{ $serviceName }}-role-{{ $.Release.Name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}
