{{- range $serviceName, $v := .Values -}}
{{- if has $serviceName $.Values.apiServices }}
{{- if index $v "enabled" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $serviceName }}
  name: {{ $serviceName }}
spec:
  {{- if (and ($.Values.ingress.className) (eq $.Values.ingress.className "nginx")) }}
  type: "ClusterIP"
  {{- else }}
  type: "NodePort"
  {{- end }}
  ports:
  - name: '{{ $.Values.service.port }}'
    port: {{ $.Values.service.port }}
    targetPort: {{ $.Values.service.port }}
  selector:
    app: {{ $serviceName }}-{{ $.Release.Name }}
---
{{/* END: if index $v "enabled" */}}
{{- end }}
{{/* END: if has $serviceName $.Values.externalServices */}}
{{- end }}
{{/* END: range $serviceName, $v := .Values*/}}
{{- end }}
