{{- range $serviceName, $v := .Values -}}
{{- if (or (eq $serviceName "raster") (eq $serviceName "stac") (eq $serviceName "vector") (eq $serviceName "vector2")) }}
{{- if index $v "enabled" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $serviceName }}
  name: {{ $serviceName }}
spec:
  {{- if (and ($.Values.ingress.className) (eq $.Values.ingress.className "alb")) }}
  type: "NodePort"
  {{- else if (and ($.Values.ingress.className) (eq $.Values.ingress.className "nginx")) }}
  type: "ClusterIP"
  {{- else }}
  type: "NodePort"
  {{- end }}
  ports:
  - name: '{{ $.Values.service.port }}'
    port: {{ $.Values.service.port }}
    targetPort: {{ $.Values.service.port }}
  selector:
    app: {{ $serviceName }}
---
{{/* END: if index $v "enabled" */}}
{{- end }}
{{/* END: if (or (eq $serviceName "raster") (eq $serviceName "stac") (eq $serviceName "vector")) */}}
{{- end }}
{{/* END: range $serviceName, $v := .Values*/}}
{{- end }}
