{{- range $serviceName, $v := .Values.apiServices -}}
{{- if index $v "enabled" }}
apiVersion: v1
kind: Service
metadata:
  {{- if $.Values.testing }}
  labels:
    app: {{ $serviceName }}-{{ $.Release.Name }}
  name: {{ $serviceName }}-{{ $.Release.Name }}
  {{- else }}
  labels:
    app: {{ $serviceName }}
  name: {{ $serviceName }}
  {{- end }}
spec:
  {{- if (and ($.Values.ingress.className) (eq $.Values.ingress.className "nginx")) }}
  type: "ClusterIP"
  {{- else }}
  type: "NodePort"
  {{- end }}
  ports:
  - name: '{{ $.Values.service.port }}'
    port: {{ $.Values.service.port }}
    targetPort: {{ $.Values.service.port }}
  selector:
    app: {{ $serviceName }}-{{ $.Release.Name }}
---
{{/* END: if index $v "enabled" */}}
{{- end }}
{{/* END: range $serviceName, $v := .Values.apiServices */}}
{{- end }}
