{{- if and .Values.ingress.enabled (eq .Values.ingress.className "traefik") }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: path-rewrite-middleware-{{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
spec:
  replacePathRegex:
    regex: "^/(raster|vector|stac|multidim)(/|$)(.*)"
    replacement: "$1/$3"
{{- end }}
