{{- if and .Values.ingress.enabled (eq .Values.ingress.className "traefik") }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-middleware-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      {{- if .Values.raster.enabled }}
      - {{ .Values.raster.ingress.path }}
      {{- end }}
      {{- if .Values.stac.enabled }}
      - {{ .Values.stac.ingress.path }}
      {{- end }}
      {{- if .Values.vector.enabled }}
      - {{ .Values.vector.ingress.path }}
      {{- end }}
      {{- if .Values.multidim.enabled }}
      - {{ .Values.multidim.ingress.path }}
      {{- end }}
{{- end }}
