{{- if and .Values.ingress.enabled (eq .Values.ingress.className "traefik") }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-middleware-{{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      {{- range $serviceName, $v := .Values }}
      {{- if has $serviceName $.Values.apiServices }}
      {{- if (index $v "enabled") }}
      - /{{ $serviceName }}
      {{- end }}
      {{- end }}
      {{- end }}
{{- end }}
