name: Bug report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    id: labels
    attributes:
      label: Labels
      description: Select labels that apply to this issue
      options:
        - label: bug
        - label: help wanted
        - label: good first issue

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
      placeholder: "Describe the expected behavior here..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened
      placeholder: "Describe what actually happened here..."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment context
      description: Add any other context about the environment you are using here
      placeholder: "Add any other environmental context here such as cloud provider, k8s version, other versions, etc..."

