name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature you are requesting
      placeholder: "Describe the feature here..."
    validations:
      required: true

  - type: checkboxes
    id: labels
    attributes:
      label: Labels
      description: Select labels that apply to this feature request
      options:
        - label: enhancement
        - label: discussion
        - label: help wanted
