apiVersion: v2
name: postgrescluster
description: A Helm chart for eoapi database dep for k8s
type: application
# The version below should match the version on the PostgresCluster CRD
# from CrunchyData's Postgres Operator
# https://access.crunchydata.com/documentation/postgres-operator/latest/releases
version: 5.7.0
appVersion: 5.7.0
force: true