{{- if .Values.stac.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: stac-{{ $.Release.Name }}
  labels:
    app: stac-{{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: stac-{{ .Release.Name }}
{{- end }}
