{
 "title": "eoAPI Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "podprefix", "label": "Pod Prefix", "query": ".*-eoapi-.*" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage Rate by Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"$podprefix$\", image!=\"\", container!=\"POD\", name!=\"\", container!=\"\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Throttling Rate by Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"$podprefix$\", container!=\"POD\", image!=\"\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Nginx Request Rate by Service @ 2m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[2m])) by(service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Memory Usage & Limits By Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"$podprefix$\", image!=\"\", container!=\"POD\", container!=\"\"}",
     "legendFormat": "usage-{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", pod=~\"$podprefix$\", container!=\"\"}",
     "legendFormat": "limit-{{pod}}"
    }
   ]
  },
  {
   "title": "eoAPI Pod Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_scheduled{pod=~'$podprefix$'})",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}