{{- if .Values.pgstacBootstrap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgstac-settings-config-{{ $.Release.Name }}
data:
  pgstac-settings.sql: |
    {{ $.Files.Get "initdb-data/settings/pgstac-settings.sql" | nindent 4 }}
---
{{- if or .Values.pgstacBootstrap.settings.loadSamples (eq .Values.pgstacBootstrap.settings.envVars.LOAD_FIXTURES "true") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb-sql-config-{{ $.Release.Name }}
data:
  initdb.sql: |
    {{- range $path, $bytes := $.Files.Glob "initdb-data/samples/*.sql"  -}}
    {{ $.Files.Get $path | nindent 4 }}
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb-json-config-{{ $.Release.Name }}
data:
  {{- range $path, $bytes := $.Files.Glob "initdb-data/samples/*.json"  -}}
  {{- base $path | nindent 2 -}}: | {{- $.Files.Get $path | nindent 4 -}}
  {{- end }}
{{- end }}
{{- end }}
