{{- if .Values.pgstacBootstrap.enabled }}
---
# This job initializes the PostgreSQL database with the necessary schema and data.
# Instead of using an initContainer in the deployment to wait for this job to complete,
# we use Helm hooks to control the execution order:
# 
# 1. The "post-install,post-upgrade" hook ensures this job runs after the postgres 
#    dependency is installed but before other resources (like deployments)
# 2. The "-5" hook-weight ensures this job runs after its ConfigMaps (weight -6)
# 3. The "before-hook-creation,hook-succeeded" delete policy ensures the job is recreated
#    on each helm install/upgrade and is cleaned up after successful completion
#
apiVersion: batch/v1
kind: Job
metadata:
  name: pgstacbootstrap
  labels:
    app: pgstacbootstrap
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
spec:
  template:
    metadata:
      labels:
        app: pgstacbootstrap
    spec:
      restartPolicy: Never
      containers:
        - name: pgstacbootstrap
          image: {{ .Values.pgstacBootstrap.image.name }}:{{ .Values.pgstacBootstrap.image.tag }}
          command: {{- toYaml .Values.pgstacBootstrap.command | nindent 12 }}
          args:
            {{- toYaml .Values.pgstacBootstrap.args | nindent 12 }}
          ports:
            - containerPort: 5432
          resources:
            {{- toYaml .Values.pgstacBootstrap.settings.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /opt/initdb/sql-data
              name: initdb-sql-volume-{{ $.Release.Name }}
            - mountPath: /opt/initdb/json-data
              name: initdb-json-volume-{{ $.Release.Name }}
            - mountPath: /opt/initdb/
              name: initdb-sh-volume-{{ $.Release.Name }}
            - mountPath: /opt/initdb/python-scripts
              name: pgstac-setup-volume-{{ $.Release.Name }}
          env:
            - name: LOAD_FIXTURES
              value: {{ .Values.pgstacBootstrap.settings.envVars.LOAD_FIXTURES | quote }}
            - name: KEEP_ALIVE
              value: {{ .Values.pgstacBootstrap.settings.envVars.KEEP_ALIVE | quote }}
            {{ include "eoapi.pgstacSecrets" . | nindent 12 }}
      volumes:
        - name: initdb-sql-volume-{{ $.Release.Name }}
          configMap:
            name: initdb-sql-config-{{ $.Release.Name }}
        - name: initdb-json-volume-{{ $.Release.Name }}
          configMap:
            name: initdb-json-config-{{ $.Release.Name }}
        - name: initdb-sh-volume-{{ $.Release.Name }}
          configMap:
            name: initdb-sh-config-{{ $.Release.Name }}
        - name: pgstac-setup-volume-{{ $.Release.Name }}
          configMap:
            name: pgstac-setup-config-{{ $.Release.Name }}
      {{- with .Values.pgstacBootstrap.settings.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pgstacBootstrap.settings.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 1
{{- end }}
