{{- if .Values.pgstacBootstrap.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: pgstacbootstrap
  labels:
    app: pgstacbootstrap
spec:
  template:
    metadata:
      labels:
        app: pgstacbootstrap
        {{- with .Values.pgstacBootstrap.settings.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            {{ if .Values.testing }}
            ['sh', '-c', 'until nc -z {{ $.Release.Name }}-pgbouncer 5432; do echo waiting for db; sleep 10; done;']
            {{ else }}
            ['sh', '-c', 'until nc -z $POSTGRES_HOST $POSTGRES_PORT; do echo waiting for db; sleep 10; done;']
            {{ end }}
          env:
          {{- with .Values.pgstacBootstrap.settings.envVars }}
            - name: POSTGRES_HOST
              value: {{ .Values.pgstacBootstrap.settings.envVars.POSTGRES_HOST | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.pgstacBootstrap.settings.envVars.POSTGRES_PORT | quote }}
          {{- end }}
      containers:
        - name: pgstacbootstrap
          image: {{ .Values.pgstacBootstrap.image.name }}:{{ .Values.pgstacBootstrap.image.tag }}
          command: {{- toYaml .Values.pgstacBootstrap.command | nindent 12 }}
          args:
            {{- toYaml .Values.pgstacBootstrap.args | nindent 12 }}
          ports:
            - containerPort: 5432
          resources:
            {{- toYaml .Values.pgstacBootstrap.settings.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /opt/initdb/sql-data
              name: initdb-sql-volume-{{ $.Release.Name }}
            - mountPath: /opt/initdb/json-data
              name: initdb-json-volume-{{ $.Release.Name }}
            - mountPath: /opt/initdb/
              name: initdb-sh-volume-{{ $.Release.Name }}
            - mountPath: /opt/initdb/python-scripts
              name: pgstac-setup-volume-{{ $.Release.Name }}
            {{- with .Values.pgstacBootstrap.settings.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.pgstacBootstrap.settings.envFrom }}
          envFrom:
            {{- with .Values.pgstacBootstrap.settings.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          env:
            - name: LOAD_FIXTURES
              value: {{ .Values.pgstacBootstrap.settings.envVars.LOAD_FIXTURES | quote }}
            - name: KEEP_ALIVE
              value: {{ .Values.pgstacBootstrap.settings.envVars.KEEP_ALIVE | quote }}
          {{- with .Values.pgstacBootstrap.settings.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          # TODO (emmanuel): to be removed when we have a generic way to
          # inject secrets in the pod
          {{- if or .Values.postgrescluster.enabled .Values.db.enabled }}
            {{ include "eoapi.pgstacSecrets" . | nindent 12 }}
          {{- end }}
      volumes:
        - name: initdb-sql-volume-{{ $.Release.Name }}
          configMap:
            name: initdb-sql-config-{{ $.Release.Name }}
        - name: initdb-json-volume-{{ $.Release.Name }}
          configMap:
            name: initdb-json-config-{{ $.Release.Name }}
        - name: initdb-sh-volume-{{ $.Release.Name }}
          configMap:
            name: initdb-sh-config-{{ $.Release.Name }}
        - name: pgstac-setup-volume-{{ $.Release.Name }}
          configMap:
            name: pgstac-setup-config-{{ $.Release.Name }}
        {{- with .Values.pgstacBootstrap.settings.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      serviceAccountName: {{ include "eoapi.serviceAccountName" . }}
      {{- with .Values.pgstacBootstrap.settings.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pgstacBootstrap.settings.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 1
{{- end }}
