{{- if include "eoapi.browserIngressEnabled" . | trim }}
{{- $mwPrefix := printf "%s-%s" .Release.Namespace .Release.Name -}}
apiVersion: {{ include "eoapi.ingressApiVersion" . }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-browser-ingress
  labels:
    app: {{ .Release.Name }}-ingress
  annotations:
    {{- if eq .Values.ingress.className "traefik" }}
    {{- if include "eoapi.browserRedirectEnabled" . | trim }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ printf "%s-browser-redirect-middleware@kubernetescrd" $mwPrefix }}
    {{- end }}
    {{- end }}
    {{- with include "eoapi.ingressCommonAnnotations" . | trim }}
    {{- . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- include "eoapi.ingressRules" (dict "root" . "pathsTemplate" "eoapi.browserIngressPaths") | nindent 4 }}
  {{- include "eoapi.ingressTls" . | nindent 2 }}
{{- end }}
