{{- $paths := include "eoapi.ingressPaths" . | trim }}
{{- if and .Values.ingress.enabled $paths }}
{{- $ingressAnnotations := .Values.ingress.annotations | default dict }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app: {{ .Release.Name }}-ingress
  annotations:
    {{- if and (eq .Values.ingress.className "nginx") (include "eoapi.nginxNeedsRewriteTarget" . | trim) }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- end }}
    {{- if eq .Values.ingress.className "traefik" }}
    {{- if and .Values.ingress.entrypoints (not (hasKey $ingressAnnotations "traefik.ingress.kubernetes.io/router.entrypoints")) }}
    traefik.ingress.kubernetes.io/router.entrypoints: {{ .Values.ingress.entrypoints | quote }}
    {{- end }}
    {{- $traefikMiddlewares := include "eoapi.ingressTraefikMiddlewares" . | trim -}}
    {{- if $traefikMiddlewares }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ $traefikMiddlewares }}
    {{- end }}
    {{- end }}
    {{- with $ingressAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- include "eoapi.ingressRules" (dict "root" . "pathsTpl" "eoapi.ingressPaths") | nindent 4 }}
  {{- include "eoapi.ingressTLS" . | nindent 2 }}
{{- end }}
