{{- if and .Values.ingress.enabled (include "eoapi.hasEnabledService" . | trim | eq "true") }}
{{- $annotations := dict -}}
{{- if and (eq .Values.ingress.className "traefik") .Values.ingress.entrypoints -}}
{{- $_ := set $annotations "traefik.ingress.kubernetes.io/router.entrypoints" (.Values.ingress.entrypoints | toString) -}}
{{- end -}}
{{- $annotations = mergeOverwrite $annotations (.Values.ingress.annotations | default dict) -}}
{{- if eq .Values.ingress.className "nginx" }}
{{- $_ := set $annotations "nginx.ingress.kubernetes.io/rewrite-target" "/$2" -}}
{{- $_ := set $annotations "nginx.ingress.kubernetes.io/use-regex" "true" -}}
{{- end }}
{{- if and (eq .Values.ingress.className "traefik") (include "eoapi.traefikStripPrefixes" . | fromJsonArray) }}
{{- $_ := set $annotations "traefik.ingress.kubernetes.io/router.middlewares" (printf "%s-%s-strip-prefix-middleware@kubernetescrd" .Release.Namespace .Release.Name) -}}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app: {{ .Release.Name }}-ingress
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hosts }}
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          {{- include "eoapi.ingressPaths" $ | nindent 10 }}
    {{- end }}
    {{- else }}
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
      http:
        paths:
          {{- include "eoapi.ingressPaths" . | nindent 10 }}
    {{- end }}
  {{- if and .Values.ingress.tls.enabled (or .Values.ingress.hosts .Values.ingress.host) }}
  tls:
    - hosts:
        {{- if .Values.ingress.hosts }}
        {{- range .Values.ingress.hosts }}
        - {{ . }}
        {{- end }}
        {{- else if .Values.ingress.host }}
        - {{ .Values.ingress.host }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}
