{{- if and .Values.ingress.enabled (eq .Values.ingress.className "traefik") }}
{{- $flags := include "eoapi.ingressFlags" . | fromJson -}}
{{- if not (empty $flags.stripPrefixes) }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-strip-prefix-middleware
  labels:
    app: {{ .Release.Name }}-ingress
spec:
  stripPrefix:
    prefixes:
      {{- range $flags.stripPrefixes }}
      - {{ . }}
      {{- end }}
{{- end }}
{{- if include "eoapi.browserRedirectEnabled" . | trim }}
{{- $browserPath := include "eoapi.browserIngressPath" . }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-browser-redirect-middleware
  labels:
    app: {{ .Release.Name }}-ingress
spec:
  redirectRegex:
    regex: "^(https?://[^/]+){{ $browserPath }}$"
    replacement: "${1}{{ $browserPath }}/"
    permanent: true
{{- end }}
{{- end }}
