apiVersion: v2
name: eoapi-support

appVersion: "0.1.6"
version: "0.1.6"

dependencies:
  # Prometheus for collection of metrics.
  # https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
  #
  - name: prometheus
    # NOTE: configuration for this dependency is handled in `eoapi-support/values.yaml.prometheus` values
    version: 25.3.1
    repository: https://prometheus-community.github.io/helm-charts

  # used to create custom metrics to autoscale on
  #
  - name: prometheus-adapter
    # NOTE: configuration for this dependency is handled in `eoapi-support/values.yaml.prometheus-adapter` values
    version: 4.7.1
    repository: https://prometheus-community.github.io/helm-charts

  # Grafana for dashboarding of metrics
  # https://github.com/grafana/helm-charts/tree/main/charts/grafana
  #
  - name: grafana
    # NOTE: configuration for this dependency is handled in `eoapi-support/values.yaml.grafana` values
    version: 7.3.3
    repository: https://grafana.github.io/helm-charts


  - name: metrics-server
    version: 7.2.8
    repository: https://charts.bitnami.com/bitnami