{{- if .Values.multidim.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: multidim-{{ $.Release.Name }}
  labels:
    app: multidim-{{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: multidim-{{ .Release.Name }}
{{- end }}
