{{- if .Values.vector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: vector-{{ $.Release.Name }}
  labels:
    app: vector-{{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: vector-{{ .Release.Name }}
{{- end }}
