{{- if .Values.raster.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: raster-envvar-configmap-{{ .Release.Name }}
data:
  {{- range $envKey, $envValue := .Values.raster.settings.envVars }}
  {{ upper $envKey }}: {{ $envValue | quote }}
  {{- end }}
{{- end }}
