{{- if .Values.raster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: raster
  labels:
    app: raster-{{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: raster-{{ .Release.Name }}
{{- end }}
