{{- if .Values.browser.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser-{{ .Release.Name }}
spec:
  replicas: {{.Values.browser.replicaCount}}
  selector:
    matchLabels:
      app: browser-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: browser-{{ .Release.Name }}
    spec:
      containers:
        - name: browser
          image: {{ .Values.browser.image.name }}:{{ .Values.browser.image.tag }}
          ports:
          - containerPort: 8080
          env:
            - name: SB_catalogUrl
              value: "/stac"
{{- end }}
