{{- if (and (.Values.browser.enabled) (not .Values.testing)  (.Values.docServer.enabled))}}
apiVersion: v1
kind: Service
metadata:
  name: browser-{{ .Release.Name }}
spec:
  selector:
    app: browser-{{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
{{- end }}
