{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eoapi.serviceAccountName" . }}
  labels:
    app: eoapi-{{ .Release.Name }}
    {{- if .Values.serviceAccount.labels }}
    {{- range $key, $value := .Values.serviceAccount.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    {{- end }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := .Values.serviceAccount.annotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
  {{- end }}
automountServiceAccountToken: {{ default true .Values.serviceAccount.automount }}
{{- end }}
